general:
  seed: 42
  device: "cuda:0"  # Options: "cuda:0", "cpu"
  outputDir: "outputs"

# Input settings
input:
  input_size: # Image dimensions, defined as tuple in yaml file instead of post-read process from str to tuple
  - 299
  - 299  
  batch_size: 4

data_transforms:
  train:
    run: True
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    random_horizontal_flip: true
    random_rotation: 20
    color_jitter:
      brightness: 0.5
      contrast: 0.2
      saturation: 0.2
      hue: 0.2
  val:
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

dataset:
  path: "data"
  classes_file: "classnames.txt"
  name: "Apple-Orange-Banana"
  version: 10

# Training settings
training:
  epochs: 25
  optimizer: "Adam"
  criterion: "CrossEntropy"
  learning_rate: 0.0001
  scheduler:
    step_size: 7
    gamma: 0.1
  early_stopping:
    patience: 5

model:
  type: "InceptionV3"


# Logging settings
logging:
  experiment_name: "Fruits Classification"
  mlflow_uri: "http://127.0.0.1:9090"
  log_artifacts: True
  log_manual_system_metrics: False

